version: '1.0'

services:
  nginx:
    image: sehattor/nginx:v1
    restart: always
    ports:
      - 443:443

  wordpress:
    image: sehattor/wordpress:v1
    restart: always
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_HOST: inception
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress

  mariadb:
    image: sehattor/mariadb:v1
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: inception
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: 'admin'
