version: '3'

services:
  nginx:
    build: requirements/nginx/
    restart: always
    ports:
      - 443:443
    networks:
      - frontend

  wordpress:
    build: requirements/wordpress/
    restart: always
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_USER_EMAIL: ${WP_ADMIN_USER_EMAIL}
      WP_ADMIN_USER_PASS: ${WP_ADMIN_USER_PASS}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}

  mariadb:
    build: requirements/mariadb/
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}

networks:
  frontend:
  backend:
