version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - wordpress_data:/var/www/html/

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_USER_EMAIL: ${WP_ADMIN_USER_EMAIL}
      WP_ADMIN_USER_PASS: ${WP_ADMIN_USER_PASS}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
    volumes:
      - wordpress_data:/var/www/html/

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}

networks:
  frontend:
  backend:


volumes:
  wordpress_data:
